name: Deploy Flask App to Azure
on:
  push:
    branches: [ "EchoSenseSite" ]
  workflow_dispatch:


concurrency:
  group: deploy-webapp
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: miwebapp  # cambia por el nombre de tu Web App
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./src
          enable-oryx-build: true 
